// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/crypto-market/auth/internal/models"
)

// PostAuthChangePasswordOKCode is the HTTP code returned for type PostAuthChangePasswordOK
const PostAuthChangePasswordOKCode int = 200

/*
PostAuthChangePasswordOK Success operation

swagger:response postAuthChangePasswordOK
*/
type PostAuthChangePasswordOK struct {

	/*
	  In: Body
	*/
	Payload *PostAuthChangePasswordOKBody `json:"body,omitempty"`
}

// NewPostAuthChangePasswordOK creates PostAuthChangePasswordOK with default headers values
func NewPostAuthChangePasswordOK() *PostAuthChangePasswordOK {

	return &PostAuthChangePasswordOK{}
}

// WithPayload adds the payload to the post auth change password o k response
func (o *PostAuthChangePasswordOK) WithPayload(payload *PostAuthChangePasswordOKBody) *PostAuthChangePasswordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth change password o k response
func (o *PostAuthChangePasswordOK) SetPayload(payload *PostAuthChangePasswordOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthChangePasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuthChangePasswordBadRequestCode is the HTTP code returned for type PostAuthChangePasswordBadRequest
const PostAuthChangePasswordBadRequestCode int = 400

/*
PostAuthChangePasswordBadRequest Incorrect data

swagger:response postAuthChangePasswordBadRequest
*/
type PostAuthChangePasswordBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthChangePasswordBadRequest creates PostAuthChangePasswordBadRequest with default headers values
func NewPostAuthChangePasswordBadRequest() *PostAuthChangePasswordBadRequest {

	return &PostAuthChangePasswordBadRequest{}
}

// WithPayload adds the payload to the post auth change password bad request response
func (o *PostAuthChangePasswordBadRequest) WithPayload(payload *models.Error) *PostAuthChangePasswordBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth change password bad request response
func (o *PostAuthChangePasswordBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthChangePasswordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuthChangePasswordUnauthorizedCode is the HTTP code returned for type PostAuthChangePasswordUnauthorized
const PostAuthChangePasswordUnauthorizedCode int = 401

/*
PostAuthChangePasswordUnauthorized Incorrect old password

swagger:response postAuthChangePasswordUnauthorized
*/
type PostAuthChangePasswordUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthChangePasswordUnauthorized creates PostAuthChangePasswordUnauthorized with default headers values
func NewPostAuthChangePasswordUnauthorized() *PostAuthChangePasswordUnauthorized {

	return &PostAuthChangePasswordUnauthorized{}
}

// WithPayload adds the payload to the post auth change password unauthorized response
func (o *PostAuthChangePasswordUnauthorized) WithPayload(payload *models.Error) *PostAuthChangePasswordUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth change password unauthorized response
func (o *PostAuthChangePasswordUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthChangePasswordUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuthChangePasswordInternalServerErrorCode is the HTTP code returned for type PostAuthChangePasswordInternalServerError
const PostAuthChangePasswordInternalServerErrorCode int = 500

/*
PostAuthChangePasswordInternalServerError Server error

swagger:response postAuthChangePasswordInternalServerError
*/
type PostAuthChangePasswordInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthChangePasswordInternalServerError creates PostAuthChangePasswordInternalServerError with default headers values
func NewPostAuthChangePasswordInternalServerError() *PostAuthChangePasswordInternalServerError {

	return &PostAuthChangePasswordInternalServerError{}
}

// WithPayload adds the payload to the post auth change password internal server error response
func (o *PostAuthChangePasswordInternalServerError) WithPayload(payload *models.Error) *PostAuthChangePasswordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth change password internal server error response
func (o *PostAuthChangePasswordInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthChangePasswordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
