// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InfoHandlerFunc turns a function with the right signature into a info handler
type InfoHandlerFunc func(InfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn InfoHandlerFunc) Handle(params InfoParams) middleware.Responder {
	return fn(params)
}

// InfoHandler interface for that can handle valid info params
type InfoHandler interface {
	Handle(InfoParams) middleware.Responder
}

// NewInfo creates a new http.Handler for the info operation
func NewInfo(ctx *middleware.Context, handler InfoHandler) *Info {
	return &Info{Context: ctx, Handler: handler}
}

/*
	Info swagger:route GET /info info

Get info
*/
type Info struct {
	Context *middleware.Context
	Handler InfoHandler
}

func (o *Info) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewInfoParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// InfoOKBody info o k body
//
// swagger:model InfoOKBody
type InfoOKBody struct {

	// info
	Info *string `json:"info,omitempty"`
}

// Validate validates this info o k body
func (o *InfoOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this info o k body based on context it is used
func (o *InfoOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *InfoOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InfoOKBody) UnmarshalBinary(b []byte) error {
	var res InfoOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
