// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DepositResponse deposit response
//
// swagger:model deposit_response
type DepositResponse struct {

	// address
	// Example: 0xabcdef1234567890abcdef1234567890abcdef12
	// Required: true
	Address *string `json:"address"`

	// id
	// Example: tx_dep_some-uuid
	// Required: true
	ID *string `json:"id"`

	// status
	// Example: pending
	// Required: true
	// Enum: ["pending","finished","cancelled"]
	Status *string `json:"status"`
}

// Validate validates this deposit response
func (m *DepositResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DepositResponse) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *DepositResponse) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

var depositResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","finished","cancelled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		depositResponseTypeStatusPropEnum = append(depositResponseTypeStatusPropEnum, v)
	}
}

const (

	// DepositResponseStatusPending captures enum value "pending"
	DepositResponseStatusPending string = "pending"

	// DepositResponseStatusFinished captures enum value "finished"
	DepositResponseStatusFinished string = "finished"

	// DepositResponseStatusCancelled captures enum value "cancelled"
	DepositResponseStatusCancelled string = "cancelled"
)

// prop value enum
func (m *DepositResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, depositResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DepositResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this deposit response based on context it is used
func (m *DepositResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DepositResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DepositResponse) UnmarshalBinary(b []byte) error {
	var res DepositResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
