// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"receiver/internal/di/providers"
	"receiver/internal/infrastructure/adapters/queues/kafka"
	"receiver/internal/infrastructure/adapters/repositories"
	"receiver/internal/presentation/web/controllers"
)

// Injectors from wire.go:

func InitializeServiceLocator() (*ServiceLocator, error) {
	v, err := providers.KafkaBrokersProvider()
	if err != nil {
		return nil, err
	}
	producer, err := kafka.NewProducer(v)
	if err != nil {
		return nil, err
	}
	ordersRepository, err := repositories.NewOrdersRepository(producer)
	if err != nil {
		return nil, err
	}
	ordersController, err := controllers.NewOrdersController(ordersRepository)
	if err != nil {
		return nil, err
	}
	serviceLocator, err := newServiceLocator(ordersRepository, ordersController)
	if err != nil {
		return nil, err
	}
	return serviceLocator, nil
}
