// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"executor/internal/di/providers"
	"executor/internal/infrastructure/adapters/queues/kafka"
	"executor/internal/infrastructure/services"
)

// Injectors from wire.go:

func InitializeServiceLocator() (*ServiceLocator, error) {
	v, err := providers.KafkaBrokersProvider()
	if err != nil {
		return nil, err
	}
	consumer, err := kafka.NewConsumer(v)
	if err != nil {
		return nil, err
	}
	producer, err := kafka.NewProducer(v)
	if err != nil {
		return nil, err
	}
	orderExecutor, err := services.NewOrderExecutor()
	if err != nil {
		return nil, err
	}
	orderProcessor, err := services.NewOrderProcessor(consumer, producer, orderExecutor)
	if err != nil {
		return nil, err
	}
	serviceLocator, err := newServiceLocator(orderProcessor)
	if err != nil {
		return nil, err
	}
	return serviceLocator, nil
}
