// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// CancelBidOKCode is the HTTP code returned for type CancelBidOK
const CancelBidOKCode int = 200

/*
CancelBidOK Successful operation

swagger:response cancelBidOK
*/
type CancelBidOK struct {

	/*
	  In: Body
	*/
	Payload *CancelBidOKBody `json:"body,omitempty"`
}

// NewCancelBidOK creates CancelBidOK with default headers values
func NewCancelBidOK() *CancelBidOK {

	return &CancelBidOK{}
}

// WithPayload adds the payload to the cancel bid o k response
func (o *CancelBidOK) WithPayload(payload *CancelBidOKBody) *CancelBidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cancel bid o k response
func (o *CancelBidOK) SetPayload(payload *CancelBidOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CancelBidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CancelBidBadRequestCode is the HTTP code returned for type CancelBidBadRequest
const CancelBidBadRequestCode int = 400

/*
CancelBidBadRequest Incorrect data

swagger:response cancelBidBadRequest
*/
type CancelBidBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCancelBidBadRequest creates CancelBidBadRequest with default headers values
func NewCancelBidBadRequest() *CancelBidBadRequest {

	return &CancelBidBadRequest{}
}

// WithPayload adds the payload to the cancel bid bad request response
func (o *CancelBidBadRequest) WithPayload(payload *models.Error) *CancelBidBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cancel bid bad request response
func (o *CancelBidBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CancelBidBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CancelBidForbiddenCode is the HTTP code returned for type CancelBidForbidden
const CancelBidForbiddenCode int = 403

/*
CancelBidForbidden No access

swagger:response cancelBidForbidden
*/
type CancelBidForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCancelBidForbidden creates CancelBidForbidden with default headers values
func NewCancelBidForbidden() *CancelBidForbidden {

	return &CancelBidForbidden{}
}

// WithPayload adds the payload to the cancel bid forbidden response
func (o *CancelBidForbidden) WithPayload(payload *models.Error) *CancelBidForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cancel bid forbidden response
func (o *CancelBidForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CancelBidForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
