// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// CreateBidOKCode is the HTTP code returned for type CreateBidOK
const CreateBidOKCode int = 200

/*
CreateBidOK Successful operation

swagger:response createBidOK
*/
type CreateBidOK struct {

	/*
	  In: Body
	*/
	Payload *CreateBidOKBody `json:"body,omitempty"`
}

// NewCreateBidOK creates CreateBidOK with default headers values
func NewCreateBidOK() *CreateBidOK {

	return &CreateBidOK{}
}

// WithPayload adds the payload to the create bid o k response
func (o *CreateBidOK) WithPayload(payload *CreateBidOKBody) *CreateBidOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create bid o k response
func (o *CreateBidOK) SetPayload(payload *CreateBidOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBidBadRequestCode is the HTTP code returned for type CreateBidBadRequest
const CreateBidBadRequestCode int = 400

/*
CreateBidBadRequest Incorrect data

swagger:response createBidBadRequest
*/
type CreateBidBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBidBadRequest creates CreateBidBadRequest with default headers values
func NewCreateBidBadRequest() *CreateBidBadRequest {

	return &CreateBidBadRequest{}
}

// WithPayload adds the payload to the create bid bad request response
func (o *CreateBidBadRequest) WithPayload(payload *models.Error) *CreateBidBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create bid bad request response
func (o *CreateBidBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBidBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateBidForbiddenCode is the HTTP code returned for type CreateBidForbidden
const CreateBidForbiddenCode int = 403

/*
CreateBidForbidden No access

swagger:response createBidForbidden
*/
type CreateBidForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateBidForbidden creates CreateBidForbidden with default headers values
func NewCreateBidForbidden() *CreateBidForbidden {

	return &CreateBidForbidden{}
}

// WithPayload adds the payload to the create bid forbidden response
func (o *CreateBidForbidden) WithPayload(payload *models.Error) *CreateBidForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create bid forbidden response
func (o *CreateBidForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateBidForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
