// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// GetTransactionsTransfersURL generates an URL for the get transactions transfers operation
type GetTransactionsTransfersURL struct {
	Currency  *string
	DateFrom  *int64
	DateTo    *int64
	Limit     *int64
	MaxAmount *float32
	MinAmount *float32
	Offset    *int64
	Operation *string
	Status    *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetTransactionsTransfersURL) WithBasePath(bp string) *GetTransactionsTransfersURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetTransactionsTransfersURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetTransactionsTransfersURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/transactions/transfers"

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var currencyQ string
	if o.Currency != nil {
		currencyQ = *o.Currency
	}
	if currencyQ != "" {
		qs.Set("currency", currencyQ)
	}

	var dateFromQ string
	if o.DateFrom != nil {
		dateFromQ = swag.FormatInt64(*o.DateFrom)
	}
	if dateFromQ != "" {
		qs.Set("date_from", dateFromQ)
	}

	var dateToQ string
	if o.DateTo != nil {
		dateToQ = swag.FormatInt64(*o.DateTo)
	}
	if dateToQ != "" {
		qs.Set("date_to", dateToQ)
	}

	var limitQ string
	if o.Limit != nil {
		limitQ = swag.FormatInt64(*o.Limit)
	}
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	var maxAmountQ string
	if o.MaxAmount != nil {
		maxAmountQ = swag.FormatFloat32(*o.MaxAmount)
	}
	if maxAmountQ != "" {
		qs.Set("max_amount", maxAmountQ)
	}

	var minAmountQ string
	if o.MinAmount != nil {
		minAmountQ = swag.FormatFloat32(*o.MinAmount)
	}
	if minAmountQ != "" {
		qs.Set("min_amount", minAmountQ)
	}

	var offsetQ string
	if o.Offset != nil {
		offsetQ = swag.FormatInt64(*o.Offset)
	}
	if offsetQ != "" {
		qs.Set("offset", offsetQ)
	}

	var operationQ string
	if o.Operation != nil {
		operationQ = *o.Operation
	}
	if operationQ != "" {
		qs.Set("operation", operationQ)
	}

	var statusQ string
	if o.Status != nil {
		statusQ = *o.Status
	}
	if statusQ != "" {
		qs.Set("status", statusQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetTransactionsTransfersURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetTransactionsTransfersURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetTransactionsTransfersURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetTransactionsTransfersURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetTransactionsTransfersURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetTransactionsTransfersURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
