// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// GetBidByIDOKCode is the HTTP code returned for type GetBidByIDOK
const GetBidByIDOKCode int = 200

/*
GetBidByIDOK Successful operation

swagger:response getBidByIdOK
*/
type GetBidByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Bid `json:"body,omitempty"`
}

// NewGetBidByIDOK creates GetBidByIDOK with default headers values
func NewGetBidByIDOK() *GetBidByIDOK {

	return &GetBidByIDOK{}
}

// WithPayload adds the payload to the get bid by Id o k response
func (o *GetBidByIDOK) WithPayload(payload *models.Bid) *GetBidByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bid by Id o k response
func (o *GetBidByIDOK) SetPayload(payload *models.Bid) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBidByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBidByIDForbiddenCode is the HTTP code returned for type GetBidByIDForbidden
const GetBidByIDForbiddenCode int = 403

/*
GetBidByIDForbidden No access

swagger:response getBidByIdForbidden
*/
type GetBidByIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBidByIDForbidden creates GetBidByIDForbidden with default headers values
func NewGetBidByIDForbidden() *GetBidByIDForbidden {

	return &GetBidByIDForbidden{}
}

// WithPayload adds the payload to the get bid by Id forbidden response
func (o *GetBidByIDForbidden) WithPayload(payload *models.Error) *GetBidByIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bid by Id forbidden response
func (o *GetBidByIDForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBidByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBidByIDNotFoundCode is the HTTP code returned for type GetBidByIDNotFound
const GetBidByIDNotFoundCode int = 404

/*
GetBidByIDNotFound Bid not found

swagger:response getBidByIdNotFound
*/
type GetBidByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBidByIDNotFound creates GetBidByIDNotFound with default headers values
func NewGetBidByIDNotFound() *GetBidByIDNotFound {

	return &GetBidByIDNotFound{}
}

// WithPayload adds the payload to the get bid by Id not found response
func (o *GetBidByIDNotFound) WithPayload(payload *models.Error) *GetBidByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bid by Id not found response
func (o *GetBidByIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBidByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
