// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// GetBidByIDHandlerFunc turns a function with the right signature into a get bid by id handler
type GetBidByIDHandlerFunc func(GetBidByIDParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBidByIDHandlerFunc) Handle(params GetBidByIDParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetBidByIDHandler interface for that can handle valid get bid by id params
type GetBidByIDHandler interface {
	Handle(GetBidByIDParams, *models.User) middleware.Responder
}

// NewGetBidByID creates a new http.Handler for the get bid by id operation
func NewGetBidByID(ctx *middleware.Context, handler GetBidByIDHandler) *GetBidByID {
	return &GetBidByID{Context: ctx, Handler: handler}
}

/*
	GetBidByID swagger:route GET /market/{bid_id} getBidById

Get bid info by id
*/
type GetBidByID struct {
	Context *middleware.Context
	Handler GetBidByIDHandler
}

func (o *GetBidByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBidByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
