// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// GetBidsOKCode is the HTTP code returned for type GetBidsOK
const GetBidsOKCode int = 200

/*
GetBidsOK Successful operation

swagger:response getBidsOK
*/
type GetBidsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Bid `json:"body,omitempty"`
}

// NewGetBidsOK creates GetBidsOK with default headers values
func NewGetBidsOK() *GetBidsOK {

	return &GetBidsOK{}
}

// WithPayload adds the payload to the get bids o k response
func (o *GetBidsOK) WithPayload(payload []*models.Bid) *GetBidsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bids o k response
func (o *GetBidsOK) SetPayload(payload []*models.Bid) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBidsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Bid, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBidsBadRequestCode is the HTTP code returned for type GetBidsBadRequest
const GetBidsBadRequestCode int = 400

/*
GetBidsBadRequest Incorrect data

swagger:response getBidsBadRequest
*/
type GetBidsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBidsBadRequest creates GetBidsBadRequest with default headers values
func NewGetBidsBadRequest() *GetBidsBadRequest {

	return &GetBidsBadRequest{}
}

// WithPayload adds the payload to the get bids bad request response
func (o *GetBidsBadRequest) WithPayload(payload *models.Error) *GetBidsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bids bad request response
func (o *GetBidsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBidsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBidsUnauthorizedCode is the HTTP code returned for type GetBidsUnauthorized
const GetBidsUnauthorizedCode int = 401

/*
GetBidsUnauthorized Unauthorized

swagger:response getBidsUnauthorized
*/
type GetBidsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBidsUnauthorized creates GetBidsUnauthorized with default headers values
func NewGetBidsUnauthorized() *GetBidsUnauthorized {

	return &GetBidsUnauthorized{}
}

// WithPayload adds the payload to the get bids unauthorized response
func (o *GetBidsUnauthorized) WithPayload(payload *models.Error) *GetBidsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bids unauthorized response
func (o *GetBidsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBidsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
