// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// GetBidsHandlerFunc turns a function with the right signature into a get bids handler
type GetBidsHandlerFunc func(GetBidsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBidsHandlerFunc) Handle(params GetBidsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetBidsHandler interface for that can handle valid get bids params
type GetBidsHandler interface {
	Handle(GetBidsParams, *models.User) middleware.Responder
}

// NewGetBids creates a new http.Handler for the get bids operation
func NewGetBids(ctx *middleware.Context, handler GetBidsHandler) *GetBids {
	return &GetBids{Context: ctx, Handler: handler}
}

/*
	GetBids swagger:route GET /bids getBids

Get bids & ask history

Returns the user's market maker requests
*/
type GetBids struct {
	Context *middleware.Context
	Handler GetBidsHandler
}

func (o *GetBids) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBidsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
