// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// PostTransactionsWithdrawHandlerFunc turns a function with the right signature into a post transactions withdraw handler
type PostTransactionsWithdrawHandlerFunc func(PostTransactionsWithdrawParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTransactionsWithdrawHandlerFunc) Handle(params PostTransactionsWithdrawParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PostTransactionsWithdrawHandler interface for that can handle valid post transactions withdraw params
type PostTransactionsWithdrawHandler interface {
	Handle(PostTransactionsWithdrawParams, *models.User) middleware.Responder
}

// NewPostTransactionsWithdraw creates a new http.Handler for the post transactions withdraw operation
func NewPostTransactionsWithdraw(ctx *middleware.Context, handler PostTransactionsWithdrawHandler) *PostTransactionsWithdraw {
	return &PostTransactionsWithdraw{Context: ctx, Handler: handler}
}

/*
	PostTransactionsWithdraw swagger:route POST /transactions/withdraw postTransactionsWithdraw

# Withdrawal request

Creates a request to withdraw cryptocurrency from the user's account
*/
type PostTransactionsWithdraw struct {
	Context *middleware.Context
	Handler PostTransactionsWithdrawHandler
}

func (o *PostTransactionsWithdraw) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTransactionsWithdrawParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
