// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// PostTransactionsDepositHandlerFunc turns a function with the right signature into a post transactions deposit handler
type PostTransactionsDepositHandlerFunc func(PostTransactionsDepositParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTransactionsDepositHandlerFunc) Handle(params PostTransactionsDepositParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PostTransactionsDepositHandler interface for that can handle valid post transactions deposit params
type PostTransactionsDepositHandler interface {
	Handle(PostTransactionsDepositParams, *models.User) middleware.Responder
}

// NewPostTransactionsDeposit creates a new http.Handler for the post transactions deposit operation
func NewPostTransactionsDeposit(ctx *middleware.Context, handler PostTransactionsDepositHandler) *PostTransactionsDeposit {
	return &PostTransactionsDeposit{Context: ctx, Handler: handler}
}

/*
	PostTransactionsDeposit swagger:route POST /transactions/deposit postTransactionsDeposit

# Deposit request

Creates a request to deposit cryptocurrency to the user's account and generates a deposit address
*/
type PostTransactionsDeposit struct {
	Context *middleware.Context
	Handler PostTransactionsDepositHandler
}

func (o *PostTransactionsDeposit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTransactionsDepositParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
