// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/h4x4d/crypto-market/main/internal/models"
)

// UpdateOrderStatusOKCode is the HTTP code returned for type UpdateOrderStatusOK
const UpdateOrderStatusOKCode int = 200

/*
UpdateOrderStatusOK Successful operation

swagger:response updateOrderStatusOK
*/
type UpdateOrderStatusOK struct {

	/*
	  In: Body
	*/
	Payload *UpdateOrderStatusOKBody `json:"body,omitempty"`
}

// NewUpdateOrderStatusOK creates UpdateOrderStatusOK with default headers values
func NewUpdateOrderStatusOK() *UpdateOrderStatusOK {

	return &UpdateOrderStatusOK{}
}

// WithPayload adds the payload to the update order status o k response
func (o *UpdateOrderStatusOK) WithPayload(payload *UpdateOrderStatusOKBody) *UpdateOrderStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order status o k response
func (o *UpdateOrderStatusOK) SetPayload(payload *UpdateOrderStatusOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOrderStatusBadRequestCode is the HTTP code returned for type UpdateOrderStatusBadRequest
const UpdateOrderStatusBadRequestCode int = 400

/*
UpdateOrderStatusBadRequest Incorrect data

swagger:response updateOrderStatusBadRequest
*/
type UpdateOrderStatusBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateOrderStatusBadRequest creates UpdateOrderStatusBadRequest with default headers values
func NewUpdateOrderStatusBadRequest() *UpdateOrderStatusBadRequest {

	return &UpdateOrderStatusBadRequest{}
}

// WithPayload adds the payload to the update order status bad request response
func (o *UpdateOrderStatusBadRequest) WithPayload(payload *models.Error) *UpdateOrderStatusBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order status bad request response
func (o *UpdateOrderStatusBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateOrderStatusForbiddenCode is the HTTP code returned for type UpdateOrderStatusForbidden
const UpdateOrderStatusForbiddenCode int = 403

/*
UpdateOrderStatusForbidden No access

swagger:response updateOrderStatusForbidden
*/
type UpdateOrderStatusForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateOrderStatusForbidden creates UpdateOrderStatusForbidden with default headers values
func NewUpdateOrderStatusForbidden() *UpdateOrderStatusForbidden {

	return &UpdateOrderStatusForbidden{}
}

// WithPayload adds the payload to the update order status forbidden response
func (o *UpdateOrderStatusForbidden) WithPayload(payload *models.Error) *UpdateOrderStatusForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update order status forbidden response
func (o *UpdateOrderStatusForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateOrderStatusForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
