// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateOrderStatusHandlerFunc turns a function with the right signature into a update order status handler
type UpdateOrderStatusHandlerFunc func(UpdateOrderStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateOrderStatusHandlerFunc) Handle(params UpdateOrderStatusParams) middleware.Responder {
	return fn(params)
}

// UpdateOrderStatusHandler interface for that can handle valid update order status params
type UpdateOrderStatusHandler interface {
	Handle(UpdateOrderStatusParams) middleware.Responder
}

// NewUpdateOrderStatus creates a new http.Handler for the update order status operation
func NewUpdateOrderStatus(ctx *middleware.Context, handler UpdateOrderStatusHandler) *UpdateOrderStatus {
	return &UpdateOrderStatus{Context: ctx, Handler: handler}
}

/*
	UpdateOrderStatus swagger:route POST /market-maker/statuses updateOrderStatus

Update order status
*/
type UpdateOrderStatus struct {
	Context *middleware.Context
	Handler UpdateOrderStatusHandler
}

func (o *UpdateOrderStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateOrderStatusParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UpdateOrderStatusOKBody update order status o k body
//
// swagger:model UpdateOrderStatusOKBody
type UpdateOrderStatusOKBody struct {

	// status
	// Example: ok
	Status string `json:"status,omitempty"`
}

// Validate validates this update order status o k body
func (o *UpdateOrderStatusOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update order status o k body based on context it is used
func (o *UpdateOrderStatusOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateOrderStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateOrderStatusOKBody) UnmarshalBinary(b []byte) error {
	var res UpdateOrderStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
