// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"receiver/internal/presentation/web/dto"
)

// NewReceiveOrderParams creates a new ReceiveOrderParams object
//
// There are no default values defined in the spec.
func NewReceiveOrderParams() ReceiveOrderParams {

	return ReceiveOrderParams{}
}

// ReceiveOrderParams contains all the bound params for the receive order operation
// typically these are obtained from a http.Request
//
// swagger:parameters receive_order
type ReceiveOrderParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Receiving order eventually to execute
	  Required: true
	  In: body
	*/
	Object *dto.Order
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewReceiveOrderParams() beforehand.
func (o *ReceiveOrderParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body dto.Order
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("object", "body", ""))
			} else {
				res = append(res, errors.NewParseError("object", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Object = &body
			}
		}
	} else {
		res = append(res, errors.Required("object", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
