// Code generated by go-swagger; DO NOT EDIT.

// Package restapi connector.fetcher
//
//	Fetches market data from exchange
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
