// Code generated by go-swagger; DO NOT EDIT.

// Package restapi market.main
//
//	Continuous market API for cryptocurrency trading and account management
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
