// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"generator/internal/infrastructure/dto"
)

// NewSendContinuousOrderParams creates a new SendContinuousOrderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSendContinuousOrderParams() *SendContinuousOrderParams {
	return &SendContinuousOrderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSendContinuousOrderParamsWithTimeout creates a new SendContinuousOrderParams object
// with the ability to set a timeout on a request.
func NewSendContinuousOrderParamsWithTimeout(timeout time.Duration) *SendContinuousOrderParams {
	return &SendContinuousOrderParams{
		timeout: timeout,
	}
}

// NewSendContinuousOrderParamsWithContext creates a new SendContinuousOrderParams object
// with the ability to set a context for a request.
func NewSendContinuousOrderParamsWithContext(ctx context.Context) *SendContinuousOrderParams {
	return &SendContinuousOrderParams{
		Context: ctx,
	}
}

// NewSendContinuousOrderParamsWithHTTPClient creates a new SendContinuousOrderParams object
// with the ability to set a custom HTTPClient for a request.
func NewSendContinuousOrderParamsWithHTTPClient(client *http.Client) *SendContinuousOrderParams {
	return &SendContinuousOrderParams{
		HTTPClient: client,
	}
}

/*
SendContinuousOrderParams contains all the parameters to send to the API endpoint

	for the send continuous order operation.

	Typically these are written to a http.Request.
*/
type SendContinuousOrderParams struct {

	/* Order.

	   The continuous order to be executed
	*/
	Order *dto.ContinuousOrder

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the send continuous order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendContinuousOrderParams) WithDefaults() *SendContinuousOrderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the send continuous order params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SendContinuousOrderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the send continuous order params
func (o *SendContinuousOrderParams) WithTimeout(timeout time.Duration) *SendContinuousOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send continuous order params
func (o *SendContinuousOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send continuous order params
func (o *SendContinuousOrderParams) WithContext(ctx context.Context) *SendContinuousOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send continuous order params
func (o *SendContinuousOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send continuous order params
func (o *SendContinuousOrderParams) WithHTTPClient(client *http.Client) *SendContinuousOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send continuous order params
func (o *SendContinuousOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrder adds the order to the send continuous order params
func (o *SendContinuousOrderParams) WithOrder(order *dto.ContinuousOrder) *SendContinuousOrderParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the send continuous order params
func (o *SendContinuousOrderParams) SetOrder(order *dto.ContinuousOrder) {
	o.Order = order
}

// WriteToRequest writes these params to a swagger request
func (o *SendContinuousOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Order != nil {
		if err := r.SetBodyParam(o.Order); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
